### ISSUE TITLE
Error: Input 'goToStep' is neither a WizardStep, StepOffset, number or string

### ISSUE THREAD

**Issue by GeorgeKagan** [madoar/ng2-archwizard#10]
When reaching the final step (`<wizard-completion-step>`) and then clicking this final step's title in the navigation, the above error is thrown.
Clicking other steps doesn't throw any errors and no navigation is taking place, as expected.

P.S. Very nice module, good work!

**Comment by madoar** [comment]
Nice to hear, that you like the module :)
It seems like you've found a bug... I'll try to fix it as soon as possible.
