### ISSUE TITLE
Receiving StaticInjectorError[ViewContainerRef] with v-3.0.0 code

### ISSUE THREAD

**Issue by acasciani** [madoar/ng2-archwizard#101]
I'm working in an Angular 5 project and pulled the Git repo down to my local environment. Here are the results of my build:
![image](https://user-images.githubusercontent.com/3029040/36347187-ee325662-141e-11e8-9c1c-43ecf03723d2.png)

Within the module file for component I have the following (pointed at the dist ng2-archwizard directory):
![image](https://user-images.githubusercontent.com/3029040/36347201-5add5686-141f-11e8-990e-2ecfacd6f185.png)

And within the component's html file:
![image](https://user-images.githubusercontent.com/3029040/36347206-7a0f1918-141f-11e8-9a4d-e1d491507e34.png)

When I re-serve the app up I get the following when I navigate to the component with the aw-wizard:
![image](https://user-images.githubusercontent.com/3029040/36347212-9364fae0-141f-11e8-91bd-f419cfc3929c.png)

If I remove the < aw-wizard > and all markup within it from the component html page, I am able to visit the component with no problem.

Any ideas on what I may be doing wrong or if this is a bug with the new release?

**Comment by madoar** [comment]
How are you adding `ng2-archwizard` to your dependencies? 
Are you using `npm install ...` or something different?
Which folder are you adding/installing?

**Comment by acasciani** [comment]
I cloned the ng2-archwizard to a local directory, ran "npm run build" within the ng2-archwizard project, then referenced the relative path to the dist folder.

![image](https://user-images.githubusercontent.com/3029040/36399427-d9d5565c-1599-11e8-8dea-c275dcf7805c.png)

**Comment by acasciani** [comment]
Update: 

I `npm install ...` into my project, then copied and pasted the dist from the cloned and built directory into the npm package and it looks to work now. This is resolved. Looking for the Angular 5 release but this will work in the meantime. Thanks!
