### ISSUE TITLE
Customize css

### ISSUE THREAD

**Issue by leandrocervelin** [madoar/ng2-archwizard#15]
Hi @madoar, 

congratulations for this job! It's really nice!
I would to use this component instead the component that we are using now. I'd like to know your opinion about the css customization. For example, I would like to customize the layout as is showed on the attached image.
![steps](https://user-images.githubusercontent.com/229497/27917632-cdee8d4e-626c-11e7-9160-8a4eaa4cb582.PNG)

Thank you

**Comment by madoar** [comment]
Nice to hear, that you like this component library :)

About your problem:
The wizard navigation bar should be relatively relatively easy to modify. 
To do this you simply need to change either one or both of the following files:
- `https://github.com/madoar/ng2-archwizard/blob/master/src/components/components/wizard-navigation-bar.component.horizontal.less`
- `https://github.com/madoar/ng2-archwizard/blob/master/src/components/components/wizard-navigation-bar.component.vertical.less`

The first file contains the design(s) for the horizontal navigation bar and the second file the design(s) for the vertical navigation bar.
More exactly you may want to take a look at the mixins `.line(...)` and `.state-circle(...)`.
`.line(...)` handles the design of the line between two steps, while `.state-circle(...)` handels the design of the circle itself.

If you have any other questions regarding the css customization feel free to ask.

**Comment by ckng** [comment]
Trying to customize the component theme also. If it is imported as module, we can't really go in and edit those *.less?

Component inheritance also does not seems like a workable solution.

**Comment by madoar** [comment]
If you want to modify the `*.less` files, you need rebuild `ng2-archwizard` and link your rebuilt version of `ng2-archwizard` into your project.
You can build `ng2-archwizard` via `npm run build`, this will create the `dist` folder with all required files.

What exactly do you mean with Component inheritance?

**Comment by ckng** [comment]
How to link the rebuilt version correctly?

**Comment by madoar** [comment]
There are two ways I know of to link the rebuilt version:

- Use `npm install --save path/to/your/ng2-archwizard/folder`
- https://docs.npmjs.com/cli/link
