### ISSUE TITLE
Add index.ts to not have to import from /dist

### ISSUE THREAD

**Issue by achimha** [madoar/ng2-archwizard#2]
The `WizardModule` is exported by the package from `ng2-archwizard/dist`. That is a bit unusual and no necessary. If you put an index.ts in the root with

`export * from ./dist;`

it should work without referring to the subdirectory.

**Comment by madoar** [comment]
@achimha thanks for you suggestion!
I'll add this to the next version release, which is `1.5.0`.

**Comment by madoar** [comment]
I've just released version `1.5.0`. If it doesn't work for you please don't hesitate to open an issue.
