### ISSUE TITLE
Changing Symbol Color

### ISSUE THREAD

**Issue by joseph-mcallister** [madoar/ng2-archwizard#20]
This isn't really an issue, but I didn't find any other way to contact you. This is perfect for what I am trying to do, but I can't find any way to change the color of the symbol (green, red, gray) to something that better fits my project. Is there any way to modify that CSS? Thanks!

**Comment by madoar** [comment]
Nice to read, that you like the wizard component :)

About your question: 
If you want to change the circle- and text colors of the different states you need to change these color values in the css of the `wizard-navigation-bar` component. 
The navigation bar has two stylesheet files:

- https://github.com/madoar/ng2-archwizard/blob/master/src/components/components/wizard-navigation-bar.component.horizontal.less
- https://github.com/madoar/ng2-archwizard/blob/master/src/components/components/wizard-navigation-bar.component.vertical.less

The first one contains the stylesheets for the horizontal layouts, while the second file contains the stylesheets for the vertical layouts.
To change the colors you just need to change the values of the corresponding variables in the first 5 lines of each file, that are not comments.

Afterwards you'll need to rebuild the modified `ng2-archwizard` library for your own use.
This can be done by `npm run build`. Next you'll need to add your own build as a dependency to your project.

I hope this answers your question. If there are still some points unclear don't hesitate to ask.

**Comment by shubhamnab** [comment]
I am not able to change the CSS components of form-wizard. Could you please help me in doing this.

**Comment by johnson512n28** [comment]
This can be done in some cases by overriding the css class in a .scss file:

:host::ng-deep aw-wizard-navigation-bar.horizontal.large-filled-symbols ul.steps-indicator li.done:after {
    color:white !important;
}

**Comment by madoar** [comment]
This issue is not up to date.
Starting with version `3.0.0` of the library I've added custom css support.

A short explanation how it works can be found [here](https://github.com/madoar/angular-archwizard#customizing-the-wizard-stylesheets), while an example for this can be found [here](https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/custom-css).
