### ISSUE TITLE
Add Wizard Step Validation

### ISSUE THREAD

**Issue by sajeelmunir** [madoar/ng2-archwizard#21]
Hi there,

Is it possible to add "Wizard Step Form Validation"?  Simply disable "Next" button until all required form fields filled? 

Thanks,

**Comment by madoar** [comment]
What do you mean with "Wizard Step Form Validation"?
If you want to add a form to one of your wizard steps and want to allow a user to go to the next step only if the content of the form is valid, this is possible.

In my opinion you have two options to do this. First you could use:
```html
...
<button type="submit" [disabled]="!heroForm.form.valid" nextStep>Next Step</button>
...
```
This disables the button, until the form is valid. 

The second approach you could use would be to use the `[canExit]` input of the wizard step:
```html
<wizard-step [canExit]="heroForm.form.valid">
...
<button type="submit" nextStep>Next Step</button>
...
</wizard-step>
```

**Comment by sajeelmunir** [comment]
Thank you

**Comment by kamlekar** [comment]
In my case, I want the form to be validated to go to next step. So, I am passing `validateForm()` inside `[canExit]` attribute. It seems this is being called multiple times which is also triggering the error messages. Hence, on init, when the fields are empty, the fields are showing errors.

How to fix this case?

**Comment by madoar** [comment]
@kamlekar I think your problem is similar to #33. If the solution for #33 doesn't work for you, please post a working example, which illustrates your problem

**Comment by janakprajapati2112** [comment]
Solutions looks good but i am facing problem at back button 
What i should have to do if i want to keep canexit event on next button only not on back button
Right now i am sending data on third step of my form, if i am on third step and click on back button , it still calls my function written on canexit

**Comment by madoar** [comment]
@janakprajapati2112 `[canExit]` also accepts a function, taking a [MovingDirection](https://github.com/madoar/angular-archwizard/blob/master/src/util/moving-direction.enum.ts) enum value, as a parameter.

If the user navigates backwards, i.e. from the third step to the second step, the function is called with `MovingDirection.Backwards`.
On the other hand, if the user navigates forwards, i.e. from the third step to the fourth step, the function is called with `MovingDirection.Forwards`.

An example, how such a function can be written, and be passed to the `[canExit]` input, can be found [here](https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/can-exit-event).
