### ISSUE TITLE
Disable navigation links (forwards and backwards)

### ISSUE THREAD

**Issue by Al-Sharif** [madoar/ng2-archwizard#22]
How can i disable links to prevent user from navigate between steps by the upper links?

**Comment by madoar** [comment]
You can disable the navigation links via the use of a `[canExit]` input on the wizard steps.
For an example, please take a look at https://madoar.github.io/ng2-archwizard-demo/#/step-event/can-exit and https://github.com/madoar/ng2-archwizard-demo/tree/master/src/app/can-exit-event.

**Comment by Al-Sharif** [comment]
Thank you, but there's no function will disable all links for all steps as option for wizard plugin ?

**Comment by madoar** [comment]
I'm not sure I understand your question.

If I understand you correct, you want an input for the wizard component that disables all navigation links for all steps?
I'm not sure what is the use of such an input? A user can only see one step at a time. Therefore it has no benefit in my eyes to add such an input. If you need such a functionality why don't you add the same `[canExit]` value/function to all wizard steps?

**Comment by Al-Sharif** [comment]
i appreciate your help but i was need to disable upper links without any condition like [canExit]  while next and previous buttons works as i implement it with conditions.

**Comment by Al-Sharif** [comment]
anyway, I disabled it with jquery by convert <a> elements to <h4> to remove the links 😄

**Comment by madoar** [comment]
Ah, ok it seems like I've misunderstood your question. If I understand you correctly you want to disable the navigation functionality inside the navigation bar, so that the user is forced to only use your navigation buttons inside the wizard steps?
This is currently not possible, but you're right this is a good idea to add!

**Comment by madoar** [comment]
Ok, I've just merged my PR for this issue (see #39).
It will still take a while until I do the next release on npm, therefore if you want to use this now, you will temporarily need to build `ng2-archwizard` yourself.
