### ISSUE TITLE
Issue importing 'ng2-archwizard' from Angular Quickstart

### ISSUE THREAD

**Issue by imagine4me** [madoar/ng2-archwizard#23]
There must be something trivial I'm overlooking, but I'm having trouble importing '**ng2-archwizard**' from within a barebones, official [Angular Quickstart](https://github.com/angular/quickstart).

If I begin with the official import instructions - `import { WizardModule } from 'ng2-archwizard';` -  after doing `npm install --save ng2-archwizard`, I get the following error:

**`zone.js:2622 GET http://localhost:3000/ng2-archwizard 404 (Not Found)`**

Then, if I add the following line - **`'ng2-archwizard': 'npm:ng2-archwizard/dist/index.js'`** - to `systemjs.config.js`, I get the following error:

**`zone.js:2622 GET http://localhost:3000/traceur 404 (Not Found)`**

Then, if I add reference to `traceur` inside `index.html`, the error slightly changes, but persists nonetheless:

**`zone.js:2622 GET http://localhost:3000/node_modules/ng2-archwizard/dist/components/ 404 (Not Found)`**

Is there something obvious I'm missing either in the way I reference the library or inside the boilerplate [Angular Quickstart](https://github.com/angular/quickstart)?

**Comment by madoar** [comment]
I must confess, that I have no experience with systemjs. 
I have always used angular-cli to generate my barebones, which uses webpack instead of systemjs.
What I've noticed is, that you've not written about the step where you've added `WizardModule` to your `AppModule`. Please check if you did this.

**Comment by imagine4me** [comment]
I did include all of the code from installation instructions + `<wizard>...</wizard>` markup in the template:

```
import { WizardModule } from 'ng2-archwizard';

@NgModule({
  imports: [
    WizardModule
  ],
})
export class Module { }
```

I guess I may just regenerate the whole thing with angular-cli if no-one ran into this.

**Comment by imagine4me** [comment]
Using `angular-cli` (with webpack) instead of angular quickstart for project shell solved the issue.

**Comment by madoar** [comment]
Nice to hear that you got it working via `angular-cli` and webpack.
Still it would be nice if someone knew how to get it working via `angular quickstart`.
If someone got it working feel free to post a comment here how you got it working so that I can extend the `README` with the related information.

**Comment by vinayistar** [comment]
Hi im getting `Unexpected value 'undefined' imported by the module 'AppModule' ` error in console. Since I have tried both from poweshell of VS and angular-cli. My problem is still not resolved.

As per @imagine4me  I m also facing problem but using node.js not system.js. I have followed full tutorial and done same as @imagine4me  has done.
Thanks in advance.. Help plz

**Comment by madoar** [comment]
I'm currently working on a new version of `ng2-archwizard`, i.e. `version 3.0.0`.
This version uses a new build script, which should make it easier to use `ng2-archwizard`.
The new version will require the use of angular 5.
If you're already using angular 5 I would appreciate it if you can build the current master branch, to see if the new version solves the problem for you.
To build the new version simply clone the repository and run `npm run build` inside a terminal of your choice.
Afterwards be sure to install the newly created `dist` folder in your target application.

**Comment by madoar** [comment]
Please be aware that the new version contains some syntactical changes.

**Comment by vinayistar** [comment]
I visited to https://github.com/madoar/ng2-archwizard/blob/master/README.md and solved previous problem but as I followed this `'aw-wizard-step' is not a known element` error but if I use <wizard> instead of <aw-wizard> it works...Can u explain why its so??

**Comment by madoar** [comment]
> but if I use instead of it works...
I don't understand: What did you use instead of it?

**Comment by vinayistar** [comment]
What I have done is I have started with https://www.npmjs.com/package/ngx-archwizard with this NPM tutorial but Later I get to know https://www.npmjs.com/package/ng2-archwizard and solved the import problem of WizardModule. 

Im Really confused with 2 NPM's. and also with this ReadME https://github.com/madoar/ng2-archwizard/blob/master/README.md

**Comment by madoar** [comment]
Ok, I understand your confusion:
- **ngx-archwizard**: This package is not hosted by me, but it is based on my code. As far as I know it is based on version `1.x.y` of `ng2-archwizard`. As you can see the last release is also quite old, i.e. 6 months.
- **ng2-archwizard**: This is the official npm package for this project, and it is hosted by me. The current release stable version is `2.1.0`.
- **the master branch on github**: This is the official github repository of the project. It contains the newest changes to the project and is currently at version `3.0.0` which is currently in development. Version `3.0.0` contains some syntactical changes, which is the reason why the README file has some changes compared to the one found on npm.
