### ISSUE TITLE
clickable steps

### ISSUE THREAD

**Issue by gate3** [madoar/ng2-archwizard#30]
Hi, Is there a way to make steps clickable.

**Comment by madoar** [comment]
What do you mean with `clickable`? Do you want to be able to select the steps in the navigation bar of the wizard? If yes, which steps should be selectable?
Currently it's possible to select all **completed** wizard steps in the navigation bar. This will transition the wizard to the selected step.

**Comment by gate3** [comment]
Thanks for the response. Clickable being completed works as well, it
doesn't defeat the validation purpose.

**Comment by madoar** [comment]
I'm currently working on the implementation of different navigation modes (see #7). This enables you to remove some limitations when doing a step transition. 
The problem when using the navigation bar for navigation purposes is, that you don't have a `finalize` callback available, like you have when using the `nextStep`, `goToStep` and `previousStep` directives. 
I'm currently thinking about how to solve this problem.
