### ISSUE TITLE
Expose the wizard as Service

### ISSUE THREAD

**Issue by ishwinder** [madoar/ng2-archwizard#31]
Expose the wizard as a service so that it can be operated dynamically as well.
Current use case that I am dealing with is the introduction of a step dynamically in forward direction into the wizard based on certain condition.

**Comment by madoar** [comment]
Are the possibly to be inserted steps previously known, and should these step always be inserted at a fixed position?
If yes, you can use `*ngIf="condition"` to only show these conditional steps in case a certain condition has been fulfilled.

**Comment by ishwinder** [comment]
Yes, they are known that they can be inserted depending upon the a particular condition in previous step.

Consider this:

1. In a 3 step wizard, a step can be inserted between step 1 and 2 depending upon some condition in step 1. This step is hidden to start with using *ngIf
2. I am step 1 and I send an event after step 1 which tells if the step can exit or not and simaltenously set the condition for new step to appear.

The new step wont appear at 2 rather it will appear after I have reached step 3 because this condition was dynamically turned on and take effect after the current request has completed. At this moment, we will need to force enable this hidden step.

I will try to demonstrate with a plunkr.

Thanks.

**Comment by madoar** [comment]
@ishwinder did you find a solution to you problem?
Sorry but I don't really understand what functionality you need, and how it should like.
I would need an example:
- to see what doesn't work currently and
- to understand how you would like to interact with the wizard.
