### ISSUE TITLE
Webpack Build Failed

### ISSUE THREAD

**Issue by ishwinder** [madoar/ng2-archwizard#32]
ERROR in ./node_modules/ng2-archwizard/index.ts
Module build failed: Error: Typescript emitted no output for /home/test/apps/test-webpack/node_modules/ng2-archwizard/index.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358

This is the error I am getting while doing a webpack build with the plugin. Any ideas ?

Thanks.

**Comment by madoar** [comment]
I think I know where this comes from. I believe the problem should be easily solvable if I rename the file `index.ts` to `index.js`. 
Can you try, if this solves the problem?

Just out of interest:
What version of typescript and angular are you using, and are you also using angular-cli?

**Comment by ishwinder** [comment]
Yups, this fixes it .. I am only typescript 2.4.1 and angular 4.3.6

**Comment by madoar** [comment]
I'm going to reopen this for now, as a reminder for me to rename the file in the main repository.
