### ISSUE TITLE
[canExit]="checkForm()" keep on getting called

### ISSUE THREAD

**Issue by mrelics** [madoar/ng2-archwizard#33]
Hi ,

I have kept this function to check whether STEP one form is Valid ( as user might do an inspect element and remove disabled from the button) to recheck.

But now the checkForm function keep getting called n number of times even though I have not initiated any action.

Please help me.

Thanks
Manish Pandit

**Comment by madoar** [comment]
I believe the reason for the multiple calls is angular checking if the value `canExit` has changed.
As far as I understand angular it rechecks each value to detect changed in the input and output values.
This is necessary to automatically propagate these changes to the visible parts of the components.

For example:
Let's assume you set the title of a wizard step via `[title]="wizardTitleVariable"`. if you then change the content of `wizardTitleVariable` you'll automatically see the change in your browser.
The reason for this is, that angular periodically rechecks the variable for changes.

If your method `checkForm()` either is kind of performance intensive, or does some state changing logic, I would suggest to not pass the boolean result of the method call to `canExit`. Instead I would suggest you to pass a lambda function to `canExit`, that takes a direction and returns a boolean. This lambda method will only be called, when the user tries to transition between steps.
An example, how this can be done, can be found here: https://github.com/madoar/ng2-archwizard-demo/tree/master/src/app/can-exit-event

**Comment by mrelics** [comment]
Hi Madoar,

Thanks it worked ..but still there is something going wrong. in my false condition the checkChange() gets called only once.

But when it is true it get called twice.

checkChange(): boolean {
    if (this.child.formG !== undefined) {
      console.log(this.child.formG.invalid);
      if (!this.child.formG.valid || this.child.formG.controls.isTCAccepted.value === false) {
        this.goAhead = false;
      } else {
        console.log(this.child.formG.controls);
        this.goAhead = true;
      }
    }
    return this.goAhead;
  }
  canExitStep2: (MovingDirection) => boolean = (direction) => {
    switch (direction) {
      case MovingDirection.Forwards:
        return this.checkChange();
    }
  }

I also created a variable goAhead instead of directly returning true /false.

Thanks
Manish Pandit

**Comment by mrelics** [comment]
Hi,

When I debug I found that when it is moving to Step i.e gotoStep. It calls the Canexit function again.

inside this WizardComponent.prototype.goToStep 

This happens 2d time .For the first time when can exit return true it goes to gotoStep and from there inside it again check can exit.

Thanks
Manish Pandit

**Comment by madoar** [comment]
I'll take a look at this, and I'll try to remove the second lambda call.

**Comment by mrelics** [comment]
Thanks a lot

**Comment by madoar** [comment]
I forgot to add a comment here, asking you to test the PR.
@mrelics I guess it works as intended?

**Comment by mrelics** [comment]
HI Madoar,

Sorry for asking you too much things , but do I need to make any additional changes in the code.

My existing code is as follow
Main Wizard 
------------
<wizard-step navigationSymbol="2"  [canExit]="CanExitStep2">
    <app-step2 [subscriptionData]="subscriptionData"></app-step2>
   </wizard-step>

 canExitStep2: (MovingDirection) => boolean = (direction) => {
    switch (direction) {
      case MovingDirection.Forwards:
        return this.checkStep2();
    }
  }

  checkStep2(): boolean {
    if (this.child2.formL !== undefined) {
      if (!this.child2.formL.valid) {
        this.toaster.toastme('E', 'Form - Step 2 need some more inputs from you to move further.', 'Subscription');
        return false;
      } else { //if user is not enabling the button through inspect element and all form data is ok create a subscription
        this.createSubscription();
        return true;
      }
    }
    return false;
  }



app Step2
------
 <button type="button"  [disabled]="!formL.valid"  nextStep> {{this.subservice.data === 'Free' ? 'Complete' : 'Next' }}</button>


What additional changes I need to do to make the new changes worked ?

I tried to use finalise and preFinalize but could not weave the right thing.

Thanks
Manish Pandit

**Comment by madoar** [comment]
@mrelics what errors do you get?
On a short look I can see the following:
- `[canExit]="CanExitStep2"` I believe this should be ` [canExit]="canExitStep2"`
- Your `switch (direction)` is missing a `default` case
- Your step doesn't seem to have a `stepTitle`.

In addition it would be nice if you could format your code and comment it inside a code environment.

**Comment by mrelics** [comment]
Hi Madoar,

I am not getting any errors , but still the recent changes which you have made to repository I want to adapt that.Here is my code.


subscription-wizard.component.html
```
<wizard  #wizard navBarLayout="large-filled-symbols">
  <wizard-step navigationSymbol="1" stepTitle="1" [canExit]="canExitStep1" >
    <app-step1></app-step1>
  </wizard-step>
  <wizard-step navigationSymbol="2"  stepTitle="2" [canExit]="canExitStep2">
    <app-step2 ></app-step2>
  </wizard-step>
  <wizard-step navigationSymbol="3" stepTitle="3" *ngIf="this.showChildRequestdata === 'Paid'">
    Content of Step 3
    <button type="button" previousStep>Previous Step</button>
    <button type="button" nextStep>Complete</button>
  </wizard-step>
 <wizard-step navigationSymbol="End" stepTitle="End">
    Complete - Thank You
  <a href="/secure/dashboard">Go to Dashboard</a>
  </wizard-step>
</wizard>

```
subscription-wizard.component.ts
```
canExitStep2: (MovingDirection) => boolean = (direction) => {
    switch (direction) {
      case MovingDirection.Forwards:
        return this.checkStep2();
    }
  }

checkStep2(): boolean {
    if (this.child2.formL !== undefined) {
      if (!this.child2.formL.valid) {
       alert('please check form values');
        return false;
      } else {
        this.createSubscription();
        return true;
      }
    }
    return false;
  }

createSubscription() {
   console.log('creating subscription')
}
```

app-step2.component.html
```
<button type="button"  [disabled]="!formL.valid"  nextStep> {{this.subservice.data === 'Free' ? 'Complete' : 'Next' }}</button>

```
Thanks

**Comment by madoar** [comment]
In theory I think this should work.
I would suggest, that you add a `default` case to your `canExitStep2` method.
If it doesn't work I need a description of what doesn't work (because you're using quite a lot of features in your code snippet: i.e. `*ngIf` on steps, step validation through a form) and a minimum "working" project, with which I can experiment.

In addition I would suggest, that you use the `wizardStep` directive on your `app-step1` and `app-step2` components. The last step also looks like it should be a `wizard-completion-step`

**Comment by mrelics** [comment]
Hi Madoar,

Thanks for your support. Your wizard is perfectly okay. I was doing some things wrongs. I am now saving the fields to the database on (stepEnter) event of Completion page.

Thanks
Manish Pandit
