### ISSUE TITLE
Allow canExit functions to return promises

### ISSUE THREAD

**Issue by ggoforth** [madoar/ng2-archwizard#38]
Upon resolving, the step would exit if resolved to something truthy, or not if something falsey.  A trivial example I can think of would be checking a proposed username against the server before you leave the step.  One I am dealing with in my app is getting a Stripe token from CC fields when we leave the step.

Or maybe there is a better pattern I should be using for these kinds of checks?

**Comment by madoar** [comment]
You're right, this is a problem case that doesn't work currently, because `canExit` currently only takes a synchronous function.
I'll take a look at this.

**Comment by pymob** [comment]
Wrap the input in a form and use an async validator for the CC field. Then you only need to pass `[canExit]=myForm.valid` to the wizard.

That way you are able to provide proper feedback immediately to the user like error messages and such.

**Comment by ggoforth** [comment]
Hmm, I'll look into that @pymob.  I'm using Stripe elements, so not positive how much control I have since the actual input is mounted by stripe.  And I like using the reactive forms `.valid` as the boolean for the step.  That being said, I think this use case of using a promise is still valid.

**Comment by ggoforth** [comment]
@madoar this is working great, by the way.  Thanks for adding this!

**Comment by madoar** [comment]
Nice to hear :)
