### ISSUE TITLE
need example for form submit using wizard

### ISSUE THREAD

**Issue by sivadinesh1** [madoar/ng2-archwizard#43]
Wizard standalone works great. with info and some html. Iam struck when trying to wrap it up with some form tags like text box. My goal is to get inputs of user and submit. 

<wizard #wizard>
    <wizard-step title="Steptitle 1">
<form (ngSubmit)="onSubmit()" #f="ngForm">
      <div class="sign-up-field">
        <input id="username" type="text" class="text-input" ngModel name="username" required placeholder="Email or username">

        
        <div class="sign-up-error" *ngIf="responsemsg?.length >0 &&
                responsemsg === 'Username does not exist'                
                ">{{responsemsg}}</div>

      </div>
</form>
</wizard-step>
</wizard>

**Comment by madoar** [comment]
I'm not sure, where the `form` tag or the input component comes in in your example?
A few weeks ago someone else asked a similar question I believe: #21.
Basically you need to wrap the content of the step inside a form. Afterwards you can just bind `form.valid` to the `[canExit]` property of the step.

**Comment by sivadinesh1** [comment]
wraping whole wizard inside a form tag throws errors. My goal is to get inputs from the form and submit to server.
specially forms like these when added inside the wizard step or outside wrapping both gives either compile time or run time errors.
<form (ngSubmit)="onSubmit()" #f="ngForm">

Can we use this wizard for my usecase of form submit?

**Comment by sivadinesh1** [comment]
This Solved my issue:
"Basically you need to wrap the content of the step, the step itself or the whole wizard inside a form. "
You can close my issue. 
One suggestion - As multi form or (wizard) based form value submit is a common usecase, example on it will greatly benefit the beginner guys like me. 
thanks for the component. It has really saved a lot of time and frustration. Great!
