### ISSUE TITLE
reset wizard on defined step index

### ISSUE THREAD

**Issue by yanlyan** [madoar/ng2-archwizard#55]
I have followed this issue fix [https://github.com/madoar/ng2-archwizard/issues/8](https://github.com/madoar/ng2-archwizard/issues/8)

but i got another error

`core.es5.js:1020 ERROR Error: Uncaught (in promise): TypeError: _this.wizard.reset is not a function
TypeError: _this.wizard.reset is not a function`

it seems function reset was not found in WizardComponent

can someone explain about this ?

**Comment by madoar** [comment]
What version of `ng2-archwizard` are you using?
In the current version, i.e. 2.0.0, I've done some large refactoring, which moved some methods to different classes/components. The `reset` method belongs to these methods.

Starting from version 2.0.0 you use the `resetWizard` directive to enable the user to reset the wizard.
For an example, please take a look at: https://github.com/madoar/ng2-archwizard-demo/tree/master/src/app/reset-wizard

**Comment by yanlyan** [comment]
I'm using version 2.0.0 and I'm just figured it out, the reset method is on the navigation. Thanks
