### ISSUE TITLE
Remove selected as alternative to selectedStep. Selected is valid html

### ISSUE THREAD

**Issue by CD-UNCC** [madoar/ng2-archwizard#56]
Say there are 10 components in a module and one uses the ng2-archwizard. All other modules will fail at runtime if they use `selected` in a select/option html component.

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
No provider for WizardStep ("ustomer:
                        <select disabled class="form-control">
                            [ERROR ->]<option selected>{{specified.customerName}}</option>
                        </select>
              "): ng:///CommissionModule/NewLocationComponent.html@27:28
Error: Template parse errors:
```

**Comment by madoar** [comment]
You're right, this can lead to a problem.
I believe it's best to also remove some other directive selectors, like `optional`, because they are too generic and used otherwise.

**Comment by madoar** [comment]
I've just opened a new PR #57, which should fix this issue.
If possible, would you please test it?

**Comment by CD-UNCC** [comment]
@madoar passes my current implementation and tests. Looks good.

**Comment by SimonJang** [comment]
Any idea when this fix will be released? I'm experiencing the same problems and am unable to actually use this module.

**Comment by madoar** [comment]
Today

**Comment by SimonJang** [comment]
Ok great. Thanks!
