### ISSUE TITLE
CSS styles

### ISSUE THREAD

**Issue by aislingvasey** [madoar/ng2-archwizard#65]
Hi Wizards Makers

(I am new to Angular so I have limited knowledge if everything is this easy but) so far using your wizard has been great!

I see you are developing external CSS capabilities for the wizard's nav steps. It would be very useful to get a new release with that functionality. 

Thanks very much
Aisling

**Comment by madoar** [comment]
Nice to hear that the wizard works great for you.

About the css capabilities:
The PR working on enabling external css capabilities (#46) still requires some changes before it can be merged.
Therefore I believe it will take some more time before this can be released. In addition enabling custom styling of the nav bar may also require some other changes to the components to prevent unexpected behavior. These changes will also need to be made before a new release can be made.

**Comment by aislingvasey** [comment]
OK, thanks for the info!
