### ISSUE TITLE
this.wizard.reset() no longer working

### ISSUE THREAD

**Issue by adskiremote** [madoar/ng2-archwizard#67]
It seems the `this.wizard.reset()` no longer works.

I receive the error - `this.wizard.reset is not a function`.  I tried the examples provided in another issue post but to no avail.  I'm able to access the Wizard component using:

`  @ViewChild(WizardComponent)
  public wizard: WizardComponent;`

But seems as though there's no reset method any more.

**Comment by madoar** [comment]
Starting with version `2.0.0` I've done some refactoring in `ng2-archwizard`. One of the made changes was to relocate the `reset` method to the `NavigationMode` classes.

The preferred way to access the reset functionality is by using the `resetWizard` directive.
This directive can be added to a button or a link. Afterwards the wizard will automatically reset when the user clicks on the element. In addition it's possible to specify a `(finalize)` input. This input takes a method, which is executed during the reset.
An example how the directive can be used can be found here: https://github.com/madoar/ng2-archwizard-demo/tree/master/src/app/reset-wizard

In case you really need to call the reset method yourself, you can find it at `this.wizard.navigation.reset()`.

**Comment by adskiremote** [comment]
Hi Madoar,

I do need to call the reset myself.  That's perfect.  Thank you very much.
