### ISSUE TITLE
Navigation Bar Color issues

### ISSUE THREAD

**Issue by AhmadShahid** [madoar/ng2-archwizard#68]
Hello

When I make a step optional its color automatically green I need a way to programmatically change a step color 

e.g if I am on step 1 and all the steps are optional now at start step 1 color should be customizable if step 1 is completed then step color should be green.

**Comment by madoar** [comment]
@AhmadShahid thank you for sharing your thoughts.
Currently this is not possible. To change the colors you would currently need to rebuild/recompile `ng2-archwizard` with changed style information.

For the future it's planned to implement what you require, i.e. a way to change the style of `ng2-archwizard` without rebuilding `ng2-archwizard`. The issue related to this is #27.
Sadly I'm currently low on available time for this project, therefore I'm currently unable to work on this.

**Comment by AhmadShahid** [comment]
@madoar  thank you for letting me know. let me give it a shot with a rebuild.

**Comment by madoar** [comment]
Closed by #92, which enables the definition of custom styles outside `ng2-archwizard` to modify the look of the wizard.
