### ISSUE TITLE
Clickable Wizard Step

### ISSUE THREAD

**Issue by furqanaziz** [madoar/ng2-archwizard#7]
Is there any chance for you to make wizard steps clickable? For example I want to click on the title or icon or number of any wizard step?

This is very nice plugin but lacking this only feature which is much needed for my project.

**Comment by furqanaziz** [comment]
We can utilize `[canExit]` and `(canEnter)` for validation purpose and avoid jumping back and fourth between un-allowed stats. What you think?

**Comment by madoar** [comment]
The question then is how do we visualize which steps can be entered in the navigation bar?
I think it should be easily possible for the user to see this.
In addition we need to take subsequent steps into account, e.g. if step 2 can't be entered step 3 and 4 should automatically not be enterable, because they likely depend on step 2, right?

**Comment by furqanaziz** [comment]
If I am on step 1 and wanna jump to step 3, It should validate just like:
- `canExit` Step 1
- `canEnter` and `canExit` Step 2
- `canEnter` Step 3
- Can do this kind of iteration.

We can do it recursively. Lets say `canExit` of Step 1 is failed we can make step 1 navigation circle red kinda and return an error via an event.

**Comment by madoar** [comment]
In addition we would need some kind of indicator that tells us if the step has been entered once, otherwise the whole wizard navigation bar will show up red when the user opens it.
Do you want to give it a try?

**Comment by madoar** [comment]
Ok, I've put some more thoughts into this.
My idea is to introduce three "navigation modes" for the wizard. These modes describe the possible behavior for the navigation between steps:

- **strict** navigation:
   The first navigation mode is strict navigation. This mode describes the status quo, i.e. the current navigation behavior of the wizard. Currently you can only navigate through the wizard steps in a linear fashion, where you can only enter the next step if all previous steps have been completed and the exit condition of your current step have been fulfilled. In this mode it is not possible to jump between different steps, i.e. move to step 3 from step 1, then go to step 2 to finally go to step 4. The only exception to this rule are optional steps, which a user can skip. Therefore you are required to do the steps in the order `1 -> 2 -> 3 -> 4`.
- **semi-strict** navigation:
   The second navigation mode is semi-strict navigation. This mode lets the user navigate between the steps in any order he likes. This means that in this navigation mode a user could complete the steps in the order `1 -> 3 -> 2 -> 4`, if the exit conditions have been fulfilled. This mode has only one restriction, where the user can enter the completion step after he has completed all previous steps. Again optional steps are skipable in this mode.
- **free** navigation:
   The third navigation mode is free navigation. This mode let's the user navigate freely between the different steps, including the completion step, in any order he desires. 

To let the wizard stay backwards compatible `strict` navigation mode will be the default mode.
What do you think, would this full your needs?

**Comment by madoar** [comment]
Ok, I've now implemented the three navigation modes and merged them to the master branch.
Before I do a new release I first want to do some of the other open issues, therefore you will need to wait a while before you can see the changes on `npm`.
In case you want to give the new modes a try feel free to build the master branch and test it.
