### ISSUE TITLE
Disable Navigation Bar not working

### ISSUE THREAD

**Issue by hpribeiro** [madoar/ng2-archwizard#73]
Disable Navigation Bar is not working or I did not write correctly? I tried True,true and TRUE with and without quote but none of this worked.

![image](https://user-images.githubusercontent.com/26658279/33024146-73e73b20-cdf1-11e7-8e21-064a3b269c38.png)

**Comment by madoar** [comment]
Interesting, it seems I don't have an example for this.
Can you please try:
```html
<wizard [disableNavigationBar]="true">
```

**Comment by Not-That-Guy** [comment]
I can also confirm that, neither disableNavigationBar="true" or [disableNavigationBar]="true" work.

**Comment by hpribeiro** [comment]
I tried  `[disableNavigationBar]="true"` @madoar, but it only worked when I put `navBarLocation=""`

**Comment by madoar** [comment]
I'm not sure, but it's possible that we have different expectations about what `disableNavigationBar` should do.

When you use `navBarLocation=""` you tell `ng2-archwizard` to not show a navigation bar.
Compared to this, `[disableNavigationBar]=""` only disables the navigation bar, i.e. prevents the user from being able to click on the labels inside the navigation bar.

**Comment by hpribeiro** [comment]
Yes I think i don't understand correctly what it does ahahaha. Sorry bro!

**Comment by gate3** [comment]
Don't know if i'm late but yes @hpribeiro  you can call the next step. Just get a reference to the ng2-wizard in your typescript function then use 

> this.wizardReference.goToNextStep()

**Comment by gate3** [comment]
On the other hand, i tried this 

> [disableNavigationBar]="true"

But i get an error that 

> an't bind to 'disableNavigationBar' since it isn't a known property of 'wizard'

**Comment by madoar** [comment]
@gate3 which version of `ng2-archwizard` are you using?
`this.wizardReference.goToNextStep()` most likely won't work, because I've moved the `goToNextStep` method to another class starting with `ng2-archwizard` version 2.
The `goToNextStep` method is now located at `this.wizardReference.navigation.goToNextStep()`.

**Comment by duminduTS** [comment]
i'm using version 2.0 so that onece i use that code it given this error message 

AppComponent.html:15 ERROR TypeError: Cannot read property 'navigation' of undefined
    at AppComponent

**Comment by wassimayari** [comment]
i have the same issue 

> TypeError: Cannot read property 'goToNextStep' of undefined
    at LoginComponent.push../src/app/login/login.component.ts.LoginComponent.updateExperienceService (login.component.ts:452
