### ISSUE TITLE
Dynamically add selectedStep to wizard-step

### ISSUE THREAD

**Issue by matiullah-netlinks** [madoar/ng2-archwizard#74]
How can I add selectedStep dynamically to wizard step?. for example I want the second wizard step to be selected by default.
here is my code

`<wizard>
    <wizard-step stepTitle="{{question.name}}" *ngFor="let question of questions">
    // code
   </wizard-step>
</wizard>`

**Comment by madoar** [comment]
I think you need to do two changes, to select the second step during initialization:
- change `navigationMode` to `free`, i.e.: `<wizard navigationMode="free">`
- set the selected step via its index: `<wizard navigationMode="free" defaultStepIndex="1">`

**Comment by matiullah-netlinks** [comment]
Thanks @madoar , worked for me

**Comment by matiullah-netlinks** [comment]
@madoar  I'd be grateful if you could help me how to mark the previous steps as completed.

**Comment by madoar** [comment]
Sadly this doesn't work automatic currently. 
The reason for this is, that you can only mark a step as completed, it it's exitable, i.e. `[canExit]` returns/is `true`, which shouldn't be the case during initialization.

The best way to achieve what you require is to set the default step to `0` and manually move the required step.
This can be done via:

```typescript
@ViewChild(WizardComponent)
public wizard: WizardComponent;

...
for (let stepIndex = 0; stepIndex < destinationStep; stepIndex++) {
    wizard.navigation.goToNextStep(null, null);
}
```

**Comment by matiullah-netlinks** [comment]
There is an error `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'goToNextStep' of undefined
TypeError: Cannot read property 'goToNextStep' of undefined`
