### ISSUE TITLE
Reset wizard

### ISSUE THREAD

**Issue by JuliaRakitina** [madoar/ng2-archwizard#8]
Is it possible to reset wizard as soon as it was finished?
I did not find this functionality in documentation. Thank you

**Comment by madoar** [comment]
Yes, this functionality is already implemented.
Take a look at the `WizardComponent`, inside it you'll find a `reset` method.
After calling it, the wizard will automatically go back to the first step.

**Comment by JuliaRakitina** [comment]
I found this method, imported WizardComponent, 
`import { WizardComponent } from "ng2-archwizard/dist/components/components/wizard.component";`
insert it into constructor 
```
  constructor(private fb:FormBuilder, private translate:TranslateService, private http:Http, toasterService:ToasterService,private wiz:WizardComponent) {
    this.toasterService = toasterService;
  }
```
and then tried to call reset() 
`this.wiz.reset();`

but it throws an error
```
core.es5.js:1084 ERROR TypeError: Cannot read property 'toArray' of undefined
    at WizardComponent.get [as allSteps] (wizard.component.js:75)
    at WizardComponent.webpackJsonp.869.WizardComponent.reset (wizard.component.js:294)
    at SafeSubscriber.http.get.map.subscribe.errTitle [as _next] (starterkit.component.ts:143)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at MapSubscriber._next (map.js:83)
    at MapSubscriber.Subscriber.next (Subscriber.js:89)
    at XMLHttpRequest.onLoad (http.es5.js:1229)
```

Maybe I should define or link it somewhere else?

**Comment by madoar** [comment]
Try this:
```typescript
import {WizardComponent} from 'ng2-archwizard';

@ViewChild(WizardComponent)
public wizard: WizardComponent;

public resetWizard(): void {
   this.wizard.reset();
}
```

For a more detailed example please take a look at the example inside the [demo](https://github.com/madoar/ng2-archwizard-demo/blob/master/src/app/pizza.component.ts).

**Comment by madoar** [comment]
The error kind of looks like as if your wizard contains no steps. To make the wizard work, it needs to contain at least one step.

**Comment by JuliaRakitina** [comment]
It contains 3 complicated steps with upload component and forms

**Comment by madoar** [comment]
Can you give me a minimum working code snippet that triggers the error?

**Comment by JuliaRakitina** [comment]
Ok, I fixed it 

```
import { WizardComponent } from 'ng2-archwizard/dist/components/components';
.....
 @ViewChild("wiz") wiz:WizardComponent;
......
public resetWizard(): void {
   this.wiz.reset();
}
```
and html 
```
<wizard #wiz navBarLayout="large-filled-symbols">
  <wizard-step navigationSymbol="1" [title]="'CHECK_DOCUMENTS'|translate" >
   ...
 </wizard-step>
.......
</wizard>
```

Thank you

**Comment by madoar** [comment]
Nice to see I could help :)
So the problem was they way the `WizardComponent` was injected?
If this issue is solved, can you please close it?

**Comment by yanlyan** [comment]
Hi @JuliaRakitina i got same issue but with different error message, what version are you using ?
