### ISSUE TITLE
Implement [canEnter] and (stepEnter) inside my custom component

### ISSUE THREAD

**Issue by nolanrigo** [madoar/ng2-archwizard#82]
Hello!

Thanks for this awesome module and time you spent on !

For my wizard, I use only custom components and I would like implement [canEnter] & (stepEnter) methods inside my custom component as object method.

I didn't find this information inside documentation, is this possible ? do you have any advices ?

Have a nice day !
Nolan Rigo

**Comment by nolanrigo** [comment]
I used the first solution and it works well ❤️. Thank you so much, you saved me a lot of try / debug / work time 😅.

**Comment by Mohit17067** [comment]
Hi, I have a specific problem. In a particular step, I sm doing something in the ngOnInit method. What I want basically is execute those things when that step is on screen. I guess this could be done with stepEnter method. I am new to all this. Can you please help @nolanrigo @madoar ?
