### ISSUE TITLE
Give an identifier to a step and use goToStep using that identifier

### ISSUE THREAD

**Issue by HemaDivami** [madoar/ng2-archwizard#83]
Hi,

I have a scenario where I have to move to a step in which sometimes the step maybe visible or maybe not. So, it will be a good idea to give an identifier to that step and move to that step so that identifier issues will not come. 

For example,
`goToStep="address"` will move to a `wizard-step` which has its identifier as `address`.

Thanks.

**Comment by madoar** [comment]
It is currently not possible to add an identifier to wizard steps, and then to navigate to them through said identifier.

What you can do is to use the index of the target step.
`goToStep` allows as an input a target step index. 
If the index changes with some logic you can also provide a method to `goToStep` that returns the index of the target step the wizard should navigate to.
