### ISSUE TITLE
Ability to wrap <wizard-step> in own component

### ISSUE THREAD

**Issue by pymob** [madoar/ng2-archwizard#9]
Found your library, which seems to be the only one to support Angular 4, so props to you for this awesome thing!
I started implementing some wizard steps and wanted to extract the wizard-steps in their own components.
However when I did this, the controls didn't show up in the wizard.

Libraries used:

- @angular/*: ^4.2.3
- typescript: 2.4.0
- ng2-archwizard= ^1.6.0

Consider this example:
    
    <wizard navBarLocation="top" class="width-80">
        <app-wizard-details></app-wizard-details>
    /* more steps here */
      <wizard-completion-step title="Conclusion" navigationSymbol="3">
      </wizard-completion-step>
    </wizard>

    /* app-wizard-details */
    <wizard-step  title="First step" navigationSymbol="1">
      <form [formGroup]="detailsForm" >
        <md-input-container>
          <input mdInput formControlName="name" type="text">
        </md-input-container>
        <md-input-container>
          <input mdInput formControlName="offerNumber" type="text">
        </md-input-container>
      </form>
      <button md-raised-button (finalize)="storeDetails()" nextStep>Next</button>
    </wizard-step>

What works is the following, but then I cannot make use of your triggers like `canExit` and `stepEnter`, since the callbacks might be defined in the child components, not in the root component:

    <wizard-step title="First step" navigationSymbol="1">
        <app-wizard-details></app-wizard-details> /* has the <form> tag as root element now */
    </wizard-step>

I'd love to see the support of wrapped wizard-steps implemented. That way, you'd be able to build complex wizards without having everything in one single file.

Oh, and: Sorry for not providing a Plunker, for some reason it won't load your library from unpkg (guess due to proxy issues)

**Comment by madoar** [comment]
For the second approach you can get an instance of your `app-wizard-details` by using `@ComponentChild`, through which you could then bind the correct `canExit` and `stepEnter` callbacks, but I must agree this is not the most comfortable approach.

About the first approach, I must confess, that I've only used your second approach as of now. 
What do you mean with "controls", that don't show up? Do you mean the navigation bar or the navigation buttons, with the directives `nextStep`, `previousStep` and so on?

**Comment by pymob** [comment]
Thanks for the quick reply and for the hint about `@ComponentChild`, didn't know about that.

With "controls" I mean each and every component like `<input/>` or `<select/>` I have defined in the `app-wizard-details` component. Also, the `wizard-navigation-bar` doesn't notice that I have defined a `<wizard-step>` in the child component, so in the given example only the `wizard-completion-step` gets registered and rendered as a step in the navigation bar.

**Comment by madoar** [comment]
It seems like I've given you the wrong decorator, I meant to write `@ContentChild`.

About the "controls" problem:
It seems like the wizard steps aren't discovered.
Can you please clone the `ng2-archwizard` project and change the lines
```typescript
  @ContentChildren(WizardStepComponent)
  public wizardSteps: QueryList<WizardStepComponent>;
```
in `wizard.component.ts` to
```typescript
  @ContentChildren(WizardStepComponent, {descendants: true})
  public wizardSteps: QueryList<WizardStepComponent>;
```

Afterwards please build `ng2-archwizard` via `npm run build` and test if this fixes the issue?
If this doesn't solve the issue, I think I'll need a minimalistic runnable example that produces this problem.

**Comment by pymob** [comment]
Alright, even with descendants enabled it doesn't work.
When you debug the call to `get allSteps(): Array<WizardStep>` the length of the array is zero still.
The example can be cloned from my repo [here](https://github.com/pymob/test-archwizard_issue9). Thank you for your time!

Oh, on a side note: are buttons with `previousStep` not enabled for the completion step? I'd like to have the ability to go back to change the input without resetting the whole wizard..

**Comment by madoar** [comment]
Yes, all navigation inside the completion step are disabled.
My idea of a completion state is a state that tells the user, that the wizard has been successfully completed. An example for this is the message you get from an online shop after you've completed your purchase, afterwards it's not possible anymore to change your chosen products or the destination of the purchase.

**Comment by madoar** [comment]
I've just experimented a little bit with your example project.
The problem seems to be that angular is unable to find the wizard steps over multiple hierarchy levels when the first level contains a `ng-content` element.
I'm not sure if angular is really unable to do that or if my approach is wrong. 

Another solution for this would be the rewrite of the `wizard-step` components to `wizardStep` directives.
These directives could then be added to custom components. At least in theory angular should then be able to use the components as wizard steps.
The problem with this approach is, that it would destroy the backwards compatibility of `ng2-archwizard` to previous versions, because the old `wizard-step` components couldn't be used anymore.
This is something I don't want.
Again I couldn't find a way to automatically add a directive to a component, without adding it manually.

Therefore the only way currently available for this is defining a custom component, that you use **inside** a `wizard-step` component, like you did in your second approach:
```html
<wizard-step title="First step" navigationSymbol="1">
    <app-wizard-details></app-wizard-details>
</wizard-step>
```

**Comment by achimha** [comment]
You could allow both the component and directive.

**Comment by madoar** [comment]
Can I do this in with a single `@ContentChildren` decorator, or do I need for each component and directive a decorator?

**Comment by madoar** [comment]
I think I've found a way to do this.
As far as I've discovered we'll need both https://angular.io/api/core/InjectionToken and https://github.com/angular/angular/issues/12758 for this.
I'll take a more detailed look at this later next week.

**Comment by pymob** [comment]
Thank you.
Regarding the wizard-completion-step: May there be any chance to introduce a directive like this?

    <wizard-completion-step enableBackLinks="true">
      <button previousStep></button>
    </wizard-completion-step>

With this, one may be able to use the back buttons to change some things.

**Comment by madoar** [comment]
Yes, such an input would be possible. I'm just not sure yet, if I want to add this as a normal `@Input` or as an directive.

**Comment by madoar** [comment]
I've just merged my second PR regarding the feature request in this issue.
Sadly I couldn't find time to extend the `README` with information about the new features yet, but it would be nice if you could test them and tell me if they agree with what you've imagined the features to be like.

If you need some examples to see how the features work please take a look at the tests.

**Comment by pymob** [comment]
Hello @madoar , I think the latest changes are really great!
I altered my example project (check it out [here](https://github.com/pymob/test-archwizard_issue9/tree/test-if-%239-fixed)).
So far I can find everything working as expected.
Awesome work, thank you!

**Comment by LKU4** [comment]
Sorry for commenting on such an old, closed issue, but I'm not sure if this was actually resolved? It seems like the discussion got a little bit derailed with unrelated problem about completionStep. As far as I can see, wizard steps nested in child components are not loaded by the wizard.

Here's the stackblitz with example:
https://stackblitz.com/edit/angular-msg3qs

There are three steps created in app.component, but only two of them are displayed - the wizard step in nested component is ignored. It'd be pretty convenient to have this working instead of juggling with [canExit] callbacks through the ViewChilds and back.

**Comment by madoar** [comment]
I agree that this would be useful, but I don't think angular supports this. 
The problem is to have angular detect the nested `wizard-step`. 
If you can get it working feel free to open a new PR with the necessary changes.
