### ISSUE TITLE
How do i change the step from the typescript?

### ISSUE THREAD

**Issue by robert589** [madoar/ng2-archwizard#97]

**Comment by sakthivelsubbarayan** [comment]
I have a same problem.I want to move the step dynamically from typescript.But  i don't see any reference from this plugin.

**Comment by sakthivelsubbarayan** [comment]
Possible of #17 @robert589

**Comment by madoar** [comment]
To manually change the current step of the wizard, you can use:

```typescript
@ViewChild(WizardComponent)
public wizard: WizardComponent;

...

this.wizard.navigation.goToStep(1);
```

For more details please take a look at #63
