### ISSUE TITLE
Can't navigate using component's typescript

### ISSUE THREAD

**Issue by GetTaxSolutions** [madoar/ng2-archwizard#99]
I want to go to the next step in component .ts file. I tried to inject WizardState in constructor but it throw this error: 

> ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[WizardComponent -> WizardState]: 
>   StaticInjectorError(Platform: core)[WizardComponent -> WizardState]: 
>     NullInjectorError: No provider for WizardState!
> Error: StaticInjectorError(AppModule)[WizardComponent -> WizardState]: 
>   StaticInjectorError(Platform: core)[WizardComponent -> WizardState]: 
>     NullInjectorError: No provider for WizardState!

I'm using Angular 5.2.1 with ng2-archwizard 2.1.0

How I can do it? Is there some example or documentation how to navigate using component or WizardState? What is the pattern to do it?

Thanks

**Comment by madoar** [comment]
This is an error in the documentation.
To access the `WizardState` object you need to use the roundabout way through the `WizardComponent`:

```typescript
@ViewChild(WizardComponent)
public wizard: WizardComponent;
...
const wizardState: WizardState = wizard.model;
```

**Comment by suhailvs** [comment]
import { Component, ViewChild } from '@angular/core';
    import { WizardComponent } from 'angular-archwizard';
    export class MyComponent {
       @ViewChild(WizardComponent)
        public wizard: WizardComponent;
        ...
        // now you can navigate next page like:
        this.wizard.navigation.goToNextStep();
